from sentence_transformers import SentenceTransformer
from typing import List
import numpy as np

class Embedding:
    def __init__(self, model_name:str="all-MiniLM-L6-v2"):
        self.model_name = model_name
        self.model = None
        self._load_model()
    def _load_model(self):
        """
        Load the embedding model based on the specified model name.
        """
        try:
            print("Model name ", self.model_name)
            self.model =SentenceTransformer(self.model_name)
            if(self.model):
                print(f"Model loaded {self.model_name} dimension is {self.get_embedding_dimension()}.")
        except Exception as e:
            print(f"An error occurred while loading the model: {e}")

    def generate_embedding(self, texts: List[str]) -> np.ndarray:
        """
        Generate embeddings for a list of texts.
        """
        if not self.model:
            raise ValueError("Model is not loaded. Please load the model before generating embeddings.")
        try:
            embeddings = self.model.encode(texts, show_progress_bar=True)
            return embeddings
        except Exception as e:
            print(f"An error occurred while generating embeddings: {e}")
            return np.array([])
        
    def get_embedding_dimension(self) -> int:
        """
        Get the dimension of the embeddings generated by the model.
        """
        if not self.model:
            raise ValueError("Model is not loaded. Please load the model to get embedding dimension.")
        return self.model.get_sentence_embedding_dimension()   
     